services:
  web:
    build: 
      dockerfile: dockerfile
    ports:
      - 5000:5000
    command: nohup python3 nerdy_web/Aplicacao_WEB/main.py > /tmp/nerdy.log 2>&1 &
    volumes:
      - /app/MiniMim

  minimim:
    build: 
      dockerfile: dockerfile
    command: nohup python3 MiniMim/MiniMim.py > /tmp/minimim.log 2>&1 &
    volumes:
      - /app/MiniMim