name: "Deploy para VPS"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v3

      - name: "Copia arquivos via SSH"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          source: "."
          target: Nerdy
      
      - name: "Verificando e matando processos antigos"
        uses: appleboy/ssh-action@v1
        timeout-minutes: 5
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          script: |
            kill_process() {
            local pattern="$1"
            local name="$2"
            local pid
            pid=$(pgrep -f "$pattern" | grep -v $$)
            if [ -n "$pid" ]; then
              echo "Matando processo antigo: $name (PID: $pid)"
              kill $pid || true
            else
              echo "Nenhum processo antigo encontrado: $name"
            fi
            }       

            kill_process "python3 MiniMim/MiniMim.py" "MiniMim"
            kill_process "python3 nerdy_web/Aplicacao_WEB/main.py" "Aplicação WEB"

      - name: "Configuração"
        uses: appleboy/ssh-action@v1
        timeout-minutes: 5
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          source: "."
          script: |
            apk add --no-cache py3-pip  # py3-pip, não só "pip"

            cd Nerdy
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            python3 nerdy_web/Aplicacao_WEB/database/init_db.py
            
      - name: "Iniciar Aplicação e MiniMim"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER_NERDY }}
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          key_format: base64
          source: "."
          script: |
            # Ativa o ambiente virtual
            source Nerdy/venv/bin/activate

            # Roda em background e mantém mesmo após SSH fechar
            sudo nohup python3 MiniMim/MiniMim.py > /var/log/minimim.log 2>&1 &
            nohup python3 nerdy_web/Aplicacao_WEB/main.py > /var/log/nerdy.log 2>&1 &